package liyihuan.app.android.androidpractice.http2

import android.util.Log
import java.lang.RuntimeException


/**
 * This file is generated by kapt, please do not edit this file */
open class ConfigRepository : BaseRepository<ConfigService>() {
    suspend fun config(): List<ChapterBean> {
//        Log.d("QWER", "run - config: ")
//        throw RuntimeException("112233")
        return apiService.config()
    }

}
