package liyihuan.app.android.androidpractice.http2


/**
 * This file is generated by kapt, please do not edit this file */
open class ConfigRepository : BaseRepository<ConfigService>() {
    suspend fun config(): List<ChapterBean> = apiService.config()
}
